name: Run Local Test and Upload Results
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  k6_transpile_bundle_test:
    name: Transpile, bundle and run
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        uses: pnpm/action-setup@v2
        with:
          version: latest
          run_install: |
            - recursive: true
              args: [--frozen-lockfile]

      - name: Transpile and bundle test script
        # Fix the ERR_OSSL_EVP_UNSUPPORTED Error
        run: |
          NODE_OPTIONS=--openssl-legacy-provider pnpm webpack

      - name: Run "get-200-status-test" test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: dist/get-200-status-test.js
          flags: --out csv=get-200-status-test.csv

      - name: Run "post-file-test" test
        uses: grafana/k6-action@v0.3.0
        with:
          filename: dist/post-file-test.js
          flags: --out json=post-file-test.json

      - name: Run "post-400-status-test" test
        uses: grafana/k6-action@v0.3.0
        with:
          # no `--out` flag, because we use custom html reporters
          filename: dist/post-400-status-test.js

      - name: Upload performance local test results
        uses: actions/upload-artifact@v3
        with:
          name: k6-report
          path: |
            get-200-status-test.csv
            post-file-test.json
            post-400-status-test.html

          if-no-files-found: error
